# Generated by Django 5.2.4 on 2025-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("down_time", models.DateTimeField(blank=True, null=True)),
                ("up_time", models.DateTimeField(blank=True, null=True)),
                ("date", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=100)),
                ("solar", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=100)),
                ("down_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkEventImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
