# Generated by Django 5.2.4 on 2025-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkeventimport",
            name="csv_file",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="networkevent",
            constraint=models.UniqueConstraint(
                fields=("name", "down_time", "up_time"), name="unique_network_event"
            ),
        ),
    ]
