# Generated by Django 5.2.4 on 2025-08-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_networkeventimport_csv_file_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="networkevent",
            name="unique_network_event",
        ),
    ]
