# Generated by Django 5.2.4 on 2025-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_networkevent_unique_network_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkeventimport",
            options={
                "verbose_name": "Network Event CSV Import",
                "verbose_name_plural": "Network Event CSV Imports",
            },
        ),
        migrations.AlterField(
            model_name="networkeventimport",
            name="csv_file",
            field=models.FileField(upload_to="uploads/events/"),
        ),
        migrations.AddConstraint(
            model_name="networkevent",
            constraint=models.UniqueConstraint(
                fields=("name", "down_time", "up_time"), name="unique_network_event"
            ),
        ),
    ]
