# Generated by Django 5.2.4 on 2025-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_networkeventimport_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="networkevent",
            name="unique_network_event",
        ),
        migrations.AddConstraint(
            model_name="networkevent",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "down_time",
                    "up_time",
                    "date",
                    "type",
                    "region",
                    "reason",
                ),
                name="unique_entire_network_event",
            ),
        ),
    ]
