# Generated by Django 5.2.4 on 2025-08-01 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_networkevent_unique_network_event_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkevent",
            options={"ordering": ["-down_time"]},
        ),
        migrations.AlterModelOptions(
            name="networkeventimport",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Network Event CSV Import",
                "verbose_name_plural": "Network Event CSV Imports",
            },
        ),
        migrations.RemoveConstraint(
            model_name="networkevent",
            name="unique_entire_network_event",
        ),
        migrations.AddField(
            model_name="networkevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="networkevent",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="networkevent",
            name="unique_hash",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="SHA256 hash for duplicate prevention",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="networkevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="created_events",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="duplicate_events",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="processed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="networkevent",
            name="down_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="networkevent",
            name="region",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="networkevent",
            name="type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="networkevent",
            index=models.Index(
                fields=["name", "down_time"], name="base_networ_name_cdc4df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkevent",
            index=models.Index(
                fields=["type", "down_time"], name="base_networ_type_475057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkevent",
            index=models.Index(
                fields=["region", "down_time"], name="base_networ_region_3f3f5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkevent",
            index=models.Index(
                fields=["down_time"], name="base_networ_down_ti_d0085e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkevent",
            index=models.Index(
                fields=["unique_hash"], name="base_networ_unique__fa28e7_idx"
            ),
        ),
    ]
