# Generated by Django 5.2.4 on 2025-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_networkevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkevent",
            name="base_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Base hash for update comparison",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="networkeventimport",
            name="updated_events",
            field=models.IntegerField(default=0),
        ),
    ]
