# Generated by Django 5.2.4 on 2025-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_networkevent_base_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkeventimport",
            name="skipped_rows_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="skipped_logs/",
                verbose_name="Skipped Rows Log",
            ),
        ),
    ]
